- apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - nginx
      - vim
      - samba
      - zsh
      - tmux
      - ntfs-3g
      - openvpn
      - iptables
      - mosh
  become: yes