- name: git Checkout vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git' 
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: Copy VIMRC
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
