- lineinfile:
        path: /etc/apt/sources.list
        line: deb https://download.zerotier.com/debian/stretch stretch main

- apt_key:
      url: https://download.zerotier.com/contact%40zerotier.com.gpg
      state: present

- apt:
    update_cache: yes
    name: 
      - apt-transport-https
      - zerotier-one
    state: present 

- service:
    name: zerotier-one
    state: started
