#- name: upgrade flatpak
#  command: flatpak update -y
#  ignore_errors: yes
- name: Debian Update
  import_tasks: debianupdate.yml
  when: (ansible_facts['distribution'] == "Debian") or
        (ansible_facts['distribution'] == "Ubuntu")
  become: yes
- name: Opensuse Update
  import_tasks: suseupdate.yml
  when: ansible_os_family == 'Suse'
  become: yes
- name: Pacman update
  import_tasks: pacmanupdate.yml
  when: ansible_distribution == 'Archlinux'
- name: Fedora update
  import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
  become: yes
- name: Phone update
  import_tasks: phoneupdate.yml
  when: ansible_user_id == 'u0_a394'